sg_datatables_bundle:
    resource: "@SgDatatablesBundle/Controller/"
    type:     annotation

admin:
    resource: "@AppBundle/Admin/Controller/"
    type:     annotation
    prefix:   /admin

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
    prefix: /admin
fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"


